# Generated by Django 2.1.3 on 2019-12-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
