# Generated by Django 2.1.3 on 2019-12-02 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191202_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
